

server:
    tomcat:
        threads:
            max: 3
            min-spare: 3
        max-connections: 4
        acceptCount: 1

    port: 58759

    undertow:
      threads:
          worker: 5000

#logging:
#    level:
#        root: trace

spring:
    #kafka配置
    kafka:
        #bootstrap-servers: 192.168.200.72:9092,192.168.200.73:9092
        #bootstrap-servers: 192.168.200.83:9092,192.168.200.84:9092
        bootstrap-servers: localhost:9092
        client-id: dc-device-flow-analyze
        consumer:
            group-id: my-consumer-group
            max-poll-records: 10
            #Kafka中没有初始偏移或如果当前偏移在服务器上不再存在时,默认区最新 ，有三个选项 【latest, earliest, none】
            auto-offset-reset: earliest
            #是否开启自动提交
            enable-auto-commit: false
            #自动提交的时间间隔
            auto-commit-interval: 1000
        listener:
            ack-mode: MANUAL_IMMEDIATE
            concurrency: 3  #推荐设置为topic的分区数
            type: BATCH #开启批量监听
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        listener:
#            direct:
#                consumers-per-queue: 5
#                prefetch: 10
            simple:
                acknowledge-mode: manual
                concurrency: 5
                batch-size: 10